#maybe implement workflow in the future idk

#on:
#  push:
#    branches:
#      - main
#      - develop
#      - "release/**"
#    paths:
#      - "src/**"
#  pull_request:
#    branches:
#      - main
#      - "release/**"
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@6.0.2
#
#      - name: Run tests
#        run: mvn test
